version: "3"
services:
  app:
    build: .
    ports: 
      - 8080:8080 
    restart: on-failure
    volumes:
      - .:/usr/src/app/
    depends_on:
      - fullstack-postgres
    networks:
      - fullstack
  fullstack-postgres:
    environment: 
        POSTGRES_PASSWORD: admin123
        POSTGRES_USER: admin
    image: "postgres:11"
    ports:
      - "5432:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
      - ./.sql:/docker-entrypoint-initdb.d/
    networks:
      - fullstack
volumes:
  my_dbdata:

networks:
  fullstack:
    driver: bridge